### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by DeqingSun** [akita11/CH55xBook#2]
on Page 5 ```そんな中、2022 年 11 月 27 日に、福井県鯖江市で開催されていた、ものづくり系展示イベント「NT 鯖江 2021」```
Should be 2021?

Not an issue but an addition: section 2.1 ```なお USB 機能が内蔵されているだけあって、内蔵オシレータの周波数精度もそ のままで± 1.5% と、そこそこよいです*5。``` The accuracy is good enough to be USB device but not USB host. The oscillator can not be re-calibrated and an external crystal is needed (confirmed with WCH engineer). 

Section 2.2 ```Pn_DIR_PU : 各ピンのプルアップ抵抗(10k Ω)が、 1 だと ON、0 だとOFF。``` The pull-up is actually 70K with an additional 10K controlled by external voltage. The 10K resistor is used to [accelerate the rising speed](http://www.wch.cn/bbs/thread-69741-1.html) in Quasi-bidirectional mode.

Section 2.2 ```CH55x ではプルダウン抵抗が 10k Ω程度ですので``` Should this be pull-up?

Section 2.2 ```データシートには詳しいことが書いていないので、実機で試してみたところでは、 UART のような波形が出力されました。``` I've not used it either. But judging from a connector on [dev board image](https://bbs.21ic.com/icview-990190-1-1.html) and [code sample](http://club.szlcsc.com/article/auther_9799_1_243032.html), it should be used for some traditional LED panels. 

Section 3.3 ```ただし CH55x のフラッシュメモリは一応データシート記載の書き換え回数の上 限が 200 回と比較的少ないので書き換えすぎには注意しましょう。``` I've never got any CH552 with flash failure. I believe I've written one chip more than 1000 times during the CH55xduino development. Thomas Z did [report](https://www.mikrocontroller.net/topic/462538?page=4#6908519) a failure. I don't remember where I saw it: The flash chip is fine with more than 200 writes for short-time usage, but the long-term storage stability decreases.

**Comment by akita11** [comment]
@DeqingSun Thanks for your info, I've update README.md for next update on book. For number of flashing, I've wrote (at least) 200 based on the value on datasheet as guaranteed value.
